In [10]:
import pandas as pd
import numpy as np

def linear_regression(x: np.array, w: np.array):
    return np.dot(x, w)

In [61]:
def cost(X: np.array, w: np.array, y: np.array):
    return np.dot(X.transponse(), (np.dot(X, w) - y)) / len(y)

In [115]:
def gradient(X, w, y, a):
    return w - (cost(X, w, y) * a)

In [214]:
#preparing data
df = pd.read_csv("Housing.csv")
y = df["price"].to_numpy()
X = df[["area", "bathrooms", "bedrooms"]].to_numpy()
ones = np.ones(len(y))[:, np.newaxis]
X = np.concatenate((np.ones(len(y), dtype=int)[:, np.newaxis], X), axis=1)
X = X.astype(float)
w = np.random.randn(4)
a = 1

In [215]:
#normalizing
n = X.mean(axis=0)
s = X.max(axis=0) - X.min(axis=0)
for i in range(1, 4):
    new_x = (X[:, i] - n[i]) / s[i]
    X[:, i] = new_x
print(X)

[[ 1.          0.15597654  0.23792049  0.20697248]
 [ 1.          0.26181847  0.90458716  0.20697248]
 [ 1.          0.33054699  0.23792049  0.00697248]
 ...
 [ 1.         -0.10519184 -0.09541284 -0.19302752]
 [ 1.         -0.15398909 -0.09541284  0.00697248]
 [ 1.         -0.08938428 -0.09541284  0.00697248]]


In [203]:
#testing
print(linear_regression(X[0], w))
print(cost(X, w, y))
print(gradient(X, w, y, a))

-0.8389019975235273
[-4766730.39614801  -149256.63114676  -161838.9145446   -101003.61086865]
[4766729.24770642  149257.31577416  161840.03581703  101003.30155262]


In [218]:
#learning
w_prev = [0, 0, 0, 0]
while not(w==w_prev).all():
    w_prev = w
    w = gradient(X, w, y, a)
print(w)
# [4766729.24770642 5510998.06466328 4158148.49337298 2034100.16884592]

[4766729.24770642 5510998.06466328 4158148.49337298 2034100.16884592]


In [217]:
#finding the weights analiticaly
w_an = np.dot(np.dot(np.linalg.inv(np.dot(X.transpose(), X)), X.transpose()), y)
print(w_an)
# [4766729.24770642 5510998.06466326 4158148.49337299 2034100.1688459]

[4766729.24770642 5510998.06466326 4158148.49337299 2034100.1688459 ]


In [219]:
#comapring
diff = (w - w_an) / w * 100
print(diff)
# [ 0.00000000e+00  1.85892795e-13 -2.68770365e-13  8.01245942e-13]
# I think this is acurate enough

[ 0.00000000e+00  1.85892795e-13 -2.68770365e-13  8.01245942e-13]
